package com.prl.backend.entity.enums;

public enum NotificationType {
    DOCUMENT_EXPIRING_SOON,
    DOCUMENT_EXPIRED,
    DOCUMENT_REJECTED,
    DOCUMENT_APPROVED,
    EPI_DELIVERY_PENDING,
    EPI_DELIVERY_CONFIRMED,
    INCIDENT_CREATED,
    INCIDENT_ASSIGNED,
    INCIDENT_STATUS_CHANGED
}
