# ── MinIO (producción) ─────────────────────────────────
# URL pública accesible desde el navegador del usuario final
# Sobreescribe el fallback definido en application.properties
app.minio.public-url=http://164.92.202.250:9000
